### ISSUE TITLE
Euclidian distance

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/streamsx.math#2]
Having a function to calculate the euclidian distance between two lists

**Comment by ddebrunner** [comment]
The method provides an incomplete list if the result is NaN, but no indication this was done.

So if this does occur, how does a caller figure out where the actual result for a pair of input values is? E.g. the values in the input at index 7 might end up anywhere from index 0 to index 7, does it matter to the caller? Can this aspect be documented in the SPLDOC.

**Comment by hildrum** [comment]
That's a different definition of "euclidean distance" than the one I'm familiar with.
I'd expect the euclidean between two lists to be the L2 norm,  that is:
`sqrt(sum (list1[i] -list2[i])^2)`.

See: http://en.wikipedia.org/wiki/Euclidean_distance

Your function is closer to what I know as the L1 distance (sometimes called the Manhattan distance or taxicab metric): `sum (abs(list1[i]-list[i]))`

Perhaps you want to rename the function?

**Comment by ddebrunner** [comment]
@hildrum Both of the functions you describe return a single value, but the SPL function @jchailloux added returns a list, seems like it's not implementing anything close to those two?

@jchailloux what is the functionality you need?

**Comment by rayglover** [comment]
@ddebrunner  [This](https://github.com/IBMStreams/streamsx.math/blob/master/com.ibm.streamsx.math/com.ibm.streamsx.functions/Functions.spl#L17) function is not the "euclidean distance" and should not be called as such.

**Comment by joergboe** [comment]
Rename function to distanceList and return always a list with size min(size(list1), size(list1))
